### model
model_name_or_path: checkpoints/DentVLM_1st_train   # Output directory from stage 1
image_resolution: 6422528

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
deepspeed: train_script/ds_z2_config.json           # Adjust deepspeed configuration based on your hardware  

### dataset
dataset: inst_data_2nd_train
template: qwen2_vl
cutoff_len: 16384 
mask_history: true
overwrite_cache: true
preprocessing_num_workers: 128
tokenized_path: tokenized_data/inst_data_2nd_train

### output
output_dir: checkpoints/DentVLM_2nd_train
logging_steps: 1
save_steps: 155
save_total_limit: 15
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 32
num_train_epochs: 5.0
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
flash_attn: fa2
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
